spring.profiles.active: dev

#tomcat/undertow端口配置
server:
  undertow: 
    accesslog:
      dir: log # Undertow access log directory.
      enabled: true  # Enable access log.
      pattern: common # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
  port: 7000
  
#日志配置
logging:
  level: 
    root: info
    org.darcy.SimpleProject.controller: debug
    org.darcy.SimpleProject.service: debug
    org.darcy.SimpleProject.dao: debug
  file: log/SpringBoot.log



spring: 
  #事务配置
  transaction: 
    rollback-on-commit-failure: true
  #数据源配置
  datasource:
    # 默认数据源
    url: jdbc:mysql://192.168.1.188:3306/thirdparty?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: hd-dev
    password: 123456
      
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
    druid: 
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: org.darcy.SimpleProject.service.* 
      aop-proxy-target-class: true
      web-stat-filter.enabled: true  #是否启用StatFilter默认值true
      stat-view-servlet.enabled: true  #是否启用StatViewServlet默认值true
  #文件上传配置
  http:
    multipart: 
      enabled: true  #默认支持文件上传 
      file-size-threshold: 0  #支持文件写入磁盘
      location: upload  # 上传文件的临时目录  
      max-file-size: 40Mb  # 最大支持文件大小  
      max-request-size: 100Mb  # 最大支持请求大小  
    
  #模板引擎
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/template
    suffix: .html
    prefix: /html/     

 #mybatis配置：dao层接口路径+sql文件mapper
mybatis:
  business: 
    type-aliases-package: org.darcy.SimpleProject.model
    mapper-locations: classpath*:mapper/**/*Mapper.xml      



  





    
